In [2]:
import numpy as np
import pandas as pd
import scipy
import scipy.stats

In [3]:
df = pd.read_csv('bicicletas-compartidas.csv')

In [4]:
df.columns

Index(['fecha', 'bicis-compartidas', 'temp-obs', 'sens-temp', 'hum', 'viento',
       'codigo-clima', 'festivo', 'findesemana', 'cuartil-ano'],
      dtype='object')

In [5]:
y = df['bicis-compartidas'].values
y

array([182, 138, 134, ..., 337, 224, 139])

In [6]:
y = np.where(y==0,1,y)

In [7]:
np.min(y)

1

In [8]:
np.max(y)

7860

In [9]:
#promedio : sum(yi)/n


In [10]:
np.mean(y)

1143.1016997817849

In [11]:
np.sum(y)/len(y)

1143.1016997817849

In [12]:
scipy.stats.mstats.hmean(y) #media armonica

241.65180305136826

In [13]:
np.median(y) #mediana

844.0

In [16]:
#Moda : valor de y que se repite con mas frecuencia
moda = np.nan
valores, conteo_valores = np.unique(y, return_counts=True)
pos = np.argmax(conteo_valores)
moda = valores[pos]
moda

46

In [17]:
valores

array([   1,    9,   10, ..., 7208, 7531, 7860])

In [18]:
conteo_valores

array([1, 1, 1, ..., 1, 1, 1])

In [19]:
df['bicis-compartidas'].mode()

0    46
dtype: int64

In [20]:
np.std(y) #desviacion estandar

1085.0768508213835

In [21]:
#revisiones 

In [24]:
y_alterado=y.copy()
y_alterado[y_alterado==max(y_alterado)]=10000000

In [25]:
print(np.mean(y))
print(np.mean(y_alterado))

1143.1016997817849
1716.9009417709888


In [26]:
print(np.median(y))
print(np.median(y_alterado))

844.0
844.0
